# Generated by Django 2.2.1 on 2019-05-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
