# Generated by Django 2.2.1 on 2019-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190531_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
